name: Issue Workflow

on:
  issues:
    types: [opened]

env:
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
  CHAT_COMPLETIONS_DEPLOYMENT_NAME: ${{ secrets.CHAT_COMPLETIONS_DEPLOYMENT_NAME }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: DEBUG print all
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: DEBUG print body
      env:
        BODY: ${{ github.event.issue.body }}
      run: echo "$BODY"
    - name: generate
      run: |
        cd generator
        mkdir -p temp
        echo "${{ github.event.issue.body }}" > temp/body.txt
        python3 --version
        cat requirements.txt
        pip3 install -r requirements.txt
        set
        python3 generator.py

